### ISSUE TITLE
Error During Data Pre-Processing + Request for Pre-Trained Model

### ISSUE THREAD

**Issue by Yassine-Fak** [aimiokab/MISR-S2#3]
Hello,

First of all, thank you for this very interesting project ! 

I have followed the installation steps described in the README and have downloaded the dataset required for training and testing.

However, when I run the data pre-processing step, I encounter the following error:

![image](https://github.com/user-attachments/assets/0194ae99-0707-4340-8c96-ca49b11d66e7)

To provide more context: I am using Python 3.8.13 and :

![image](https://github.com/user-attachments/assets/82627a05-9521-48cc-a662-d0e7960f7c99)

Could you please help me troubleshoot this issue?

Additionally, would it be possible for you to provide a pre-trained model? This would allow me to conduct some tests without having to retrain the model from scratch.

Thank you in advance for your assistance!

Best regards

**Comment by hubert10** [comment]
Hi Yassine, your issue can easily be fixed by adding the __init__.py file in all the sub-folders afterward you will have to deal with correct imports. I was able to fix that. My only concern is the "data_gen/preprocess_data.py" when I run it almost all preprossed data files are generated except the pickle files, there are some errors which are due to some variables used which are not defined anywhere in the above code and I am struggling to understand those variables.

**Comment by nshaud** [comment]
@Yassine-Fak it should be fixed in the latest version of the repo.
